package org.bouncycastle.oer.its.template;

import com.amplitude.android.TrackingOptions;
import org.bouncycastle.asn1.DERBitString;
import org.bouncycastle.cms.CMSAttributeTableGenerator;
import org.bouncycastle.oer.OERDefinition;

/* JADX INFO: loaded from: classes3.dex */
public class IEEE1609dot2 {
    public static final OERDefinition.Builder AesCcmCiphertext;
    public static final OERDefinition.Builder Certificate;
    public static final OERDefinition.Builder CertificateBase;
    public static final OERDefinition.Builder CertificateId;
    public static final OERDefinition.Builder CertificateType;
    public static final OERDefinition.Builder ContributedExtensionBlock;
    public static final OERDefinition.Builder Countersignature;
    public static final OERDefinition.Builder EncryptedData;
    public static final OERDefinition.Builder EncryptedDataEncryptionKey;
    public static final OERDefinition.Builder EndEntityType;
    public static final OERDefinition.Builder EtsiOriginatingHeaderInfoExtension;
    public static final OERDefinition.Builder HashedData;
    public static final OERDefinition.Builder HeaderInfo;
    public static final OERDefinition.Builder HeaderInfoContributorId;
    public static final OERDefinition.Builder Ieee1609Dot2Content;
    public static final OERDefinition.Builder Ieee1609Dot2Data;
    public static final OERDefinition.Builder IssuerIdentifier;
    public static final OERDefinition.Builder LinkageData;
    public static final OERDefinition.Builder MissingCrlIdentifier;
    public static final OERDefinition.Builder PKRecipientInfo;
    public static final OERDefinition.Builder PduFunctionalType;
    public static final OERDefinition.Builder PreSharedKeyRecipientInfo;
    public static final OERDefinition.Builder PsidGroupPermissions;
    public static final OERDefinition.Builder RecipientInfo;
    public static final OERDefinition.Builder SequenceOfCertificate;
    public static final OERDefinition.Builder SequenceOfPsidGroupPermissions;
    public static final OERDefinition.Builder SequenceOfRecipientInfo;
    public static final OERDefinition.Builder SignedData;
    public static final OERDefinition.Builder SignedDataPayload;
    public static final OERDefinition.Builder SignerIdentifier;
    public static final OERDefinition.Builder SubjectPermissions;
    public static final OERDefinition.Builder SymmRecipientInfo;
    public static final OERDefinition.Builder SymmetricCiphertext;
    public static final OERDefinition.Builder ToBeSignedCertificate;
    public static final OERDefinition.Builder ToBeSignedData;
    public static final OERDefinition.Builder VerificationKeyIndicator;
    public static final OERDefinition.Element certificate;
    public static final OERDefinition.Element tbsCertificate;

    static {
        OERDefinition.Builder builderInteger = OERDefinition.integer(0L, 255L);
        PduFunctionalType = builderInteger;
        OERDefinition.Builder builderChoice = OERDefinition.choice(OERDefinition.octets(32).label("sha256HashedData"), OERDefinition.extension(), OERDefinition.octets(48).label("sha384HashedData"), OERDefinition.octets(32).label("reserved"));
        HashedData = builderChoice;
        OERDefinition.Builder builderSeq = OERDefinition.seq(Ieee1609Dot2BaseTypes.HashedId3.label("cracaId"), Ieee1609Dot2BaseTypes.CrlSeries.label("crlSeries"), OERDefinition.extension());
        MissingCrlIdentifier = builderSeq;
        OERDefinition.Builder builderInteger2 = OERDefinition.integer(0L, 255L);
        HeaderInfoContributorId = builderInteger2;
        OERDefinition.Builder builderSeq2 = OERDefinition.seq(builderInteger2.label("id"), OERDefinition.extension());
        EtsiOriginatingHeaderInfoExtension = builderSeq2;
        OERDefinition.Builder builderSeq3 = OERDefinition.seq(builderInteger2, OERDefinition.seqof(builderSeq2));
        ContributedExtensionBlock = builderSeq3;
        OERDefinition.Builder builder = Ieee1609Dot2BaseTypes.HashedId8;
        PreSharedKeyRecipientInfo = builder;
        OERDefinition.Builder builderChoice2 = OERDefinition.choice(Ieee1609Dot2BaseTypes.EciesP256EncryptedKey.label("eciesNistP256"), Ieee1609Dot2BaseTypes.EciesP256EncryptedKey.label("eciesBrainpoolP256r1"), OERDefinition.extension());
        EncryptedDataEncryptionKey = builderChoice2;
        OERDefinition.Builder builderSeq4 = OERDefinition.seq(Ieee1609Dot2BaseTypes.HashedId8.label("recipientId"), builderChoice2.label("encKey"));
        PKRecipientInfo = builderSeq4;
        OERDefinition.Builder builderSeq5 = OERDefinition.seq(OERDefinition.octets(12).label("nonce"), OERDefinition.opaque().label("ccmCiphertext"));
        AesCcmCiphertext = builderSeq5;
        OERDefinition.Builder builderChoice3 = OERDefinition.choice(builderSeq5.label("aes128ccm"), OERDefinition.extension());
        SymmetricCiphertext = builderChoice3;
        OERDefinition.Builder builderSeq6 = OERDefinition.seq(Ieee1609Dot2BaseTypes.HashedId8.label("recipientId"), builderChoice3.label("encKey"));
        SymmRecipientInfo = builderSeq6;
        OERDefinition.Builder builderChoice4 = OERDefinition.choice(builder.label("pskRecipInfo"), builderSeq6.label("symmRecipInfo"), builderSeq4.label("certRecipInfo"), builderSeq4.label("signedDataRecipInfo"), builderSeq4.label("rekRecipInfo"));
        RecipientInfo = builderChoice4;
        OERDefinition.Builder builderSeqof = OERDefinition.seqof(builderChoice4);
        SequenceOfRecipientInfo = builderSeqof;
        OERDefinition.Builder builderSeq7 = OERDefinition.seq(builderSeqof.label("recipients"), builderChoice3.label("ciphertext"));
        EncryptedData = builderSeq7;
        OERDefinition.Builder builderDefaultValue = OERDefinition.bitString(8L).defaultValue(new DERBitString(new byte[]{0}, 0));
        EndEntityType = builderDefaultValue;
        OERDefinition.Builder builderLabel = OERDefinition.choice(Ieee1609Dot2BaseTypes.SequenceOfPsidSspRange, OERDefinition.nullValue(), OERDefinition.extension()).label("SubjectPermissions");
        SubjectPermissions = builderLabel;
        OERDefinition.Builder builderLabel2 = OERDefinition.choice(Ieee1609Dot2BaseTypes.PublicVerificationKey, Ieee1609Dot2BaseTypes.EccP256CurvePoint, OERDefinition.extension()).label("VerificationKeyIndicator");
        VerificationKeyIndicator = builderLabel2;
        OERDefinition.Builder builderLabel3 = OERDefinition.seq(builderLabel, OERDefinition.integer(1L), OERDefinition.integer(0L), builderDefaultValue).label("PsidGroupPermissions");
        PsidGroupPermissions = builderLabel3;
        OERDefinition.Builder builderLabel4 = OERDefinition.seqof(builderLabel3).label("SequenceOfPsidGroupPermissions");
        SequenceOfPsidGroupPermissions = builderLabel4;
        OERDefinition.Builder builderLabel5 = OERDefinition.seq(Ieee1609Dot2BaseTypes.IValue, Ieee1609Dot2BaseTypes.LinkageValue, OERDefinition.optional(Ieee1609Dot2BaseTypes.GroupLinkageValue), OERDefinition.extension()).label("LinkageData");
        LinkageData = builderLabel5;
        OERDefinition.Builder builderLabel6 = OERDefinition.choice(builderLabel5, Ieee1609Dot2BaseTypes.Hostname, OERDefinition.octets(1, 64).label("binaryId"), OERDefinition.nullValue(), OERDefinition.extension()).label("CertificateId");
        CertificateId = builderLabel6;
        OERDefinition.Builder builderLabel7 = OERDefinition.seq(builderLabel6.labelPrefix("id"), Ieee1609Dot2BaseTypes.HashedId3.labelPrefix("cracaId"), Ieee1609Dot2BaseTypes.CrlSeries.labelPrefix("crlSeries"), Ieee1609Dot2BaseTypes.ValidityPeriod.labelPrefix("validityPeriod"), OERDefinition.optional(Ieee1609Dot2BaseTypes.GeographicRegion.labelPrefix(TrackingOptions.AMP_TRACKING_OPTION_REGION), Ieee1609Dot2BaseTypes.SubjectAssurance.labelPrefix("assuranceLevel"), Ieee1609Dot2BaseTypes.SequenceOfPsidSsp.labelPrefix("appPermissions"), builderLabel4.labelPrefix("certIssuePermissions"), builderLabel4.labelPrefix("certRequestPermissions"), OERDefinition.nullValue().labelPrefix("canRequestRollover"), Ieee1609Dot2BaseTypes.PublicEncryptionKey.labelPrefix("encryptionKey")), builderLabel2.labelPrefix("verifyKeyIndicator"), OERDefinition.extension()).label("ToBeSignedCertificate");
        ToBeSignedCertificate = builderLabel7;
        OERDefinition.Builder builderLabel8 = OERDefinition.choice(Ieee1609Dot2BaseTypes.HashedId8, Ieee1609Dot2BaseTypes.HashAlgorithm, OERDefinition.extension(), Ieee1609Dot2BaseTypes.HashedId8).label("IssuerIdentifier");
        IssuerIdentifier = builderLabel8;
        OERDefinition.Builder builderLabel9 = OERDefinition.enumeration(OERDefinition.enumItem("explicit"), OERDefinition.enumItem("implicit"), OERDefinition.extension()).label("CertificateType");
        CertificateType = builderLabel9;
        OERDefinition.Builder builderLabel10 = OERDefinition.seq(Ieee1609Dot2BaseTypes.UINT8, builderLabel9, builderLabel8, builderLabel7, OERDefinition.optional(Ieee1609Dot2BaseTypes.Signature)).label("CertificateBase");
        CertificateBase = builderLabel10;
        OERDefinition.Builder builderLabel11 = builderLabel10.copy().label("Certificate(CertificateBase)");
        Certificate = builderLabel11;
        OERDefinition.Builder builderSeqof2 = OERDefinition.seqof(builderLabel11);
        SequenceOfCertificate = builderSeqof2;
        OERDefinition.Builder builderSeq8 = OERDefinition.seq(Ieee1609Dot2BaseTypes.Psid.label("psid"), OERDefinition.optional(Ieee1609Dot2BaseTypes.Time64.label("generationTime"), Ieee1609Dot2BaseTypes.Time64.label("expiryTime"), Ieee1609Dot2BaseTypes.ThreeDLocation.label("generationLocation"), Ieee1609Dot2BaseTypes.HashedId3.label("p2pcdLearningRequest"), builderSeq.label("missingCrlIdentifier"), Ieee1609Dot2BaseTypes.EncryptionKey.label("encryptionKey")), OERDefinition.extension(), OERDefinition.optional(Ieee1609Dot2BaseTypes.SequenceOfHashedId3.label("inlineP2pcdRequest"), builderLabel11.label("requestedCertificate"), builderInteger.label("pduFunctionalType"), builderSeq3.label("contributedExtensions")));
        HeaderInfo = builderSeq8;
        OERDefinition.Builder builderChoice5 = OERDefinition.choice(Ieee1609Dot2BaseTypes.HashedId8.label(CMSAttributeTableGenerator.DIGEST), builderSeqof2, OERDefinition.nullValue().label("self"), OERDefinition.extension());
        SignerIdentifier = builderChoice5;
        OERDefinition.MutableBuilder mutableBuilder = new OERDefinition.MutableBuilder(OERDefinition.BaseType.SEQ);
        ToBeSignedData = mutableBuilder;
        OERDefinition.Builder builderSeq9 = OERDefinition.seq(Ieee1609Dot2BaseTypes.HashAlgorithm.label("hashId"), mutableBuilder.label("tbsData"), builderChoice5.label("signer"), Ieee1609Dot2BaseTypes.Signature.label("signature"));
        SignedData = builderSeq9;
        OERDefinition.Builder builderChoice6 = OERDefinition.choice(OERDefinition.opaque().label("unsecuredData"), builderSeq9.label("signedData"), builderSeq7.label("encryptedData"), OERDefinition.opaque().label("signedCertificateRequest"), OERDefinition.extension());
        Ieee1609Dot2Content = builderChoice6;
        Countersignature = OERDefinition.seq(Ieee1609Dot2BaseTypes.UINT8.label("protocolVersion"), builderChoice6.label("content"));
        OERDefinition.Builder builderSeq10 = OERDefinition.seq(Ieee1609Dot2BaseTypes.UINT8.label("protocolVersion"), builderChoice6.label("content"));
        Ieee1609Dot2Data = builderSeq10;
        OERDefinition.Builder builderSeq11 = OERDefinition.seq(OERDefinition.optional(builderSeq10.label("data"), builderChoice.label("extDataHash")), OERDefinition.extension());
        SignedDataPayload = builderSeq11;
        certificate = builderLabel11.build();
        tbsCertificate = builderLabel7.build();
        mutableBuilder.addItemsAndFreeze(builderSeq11.label("payload"), builderSeq8.label("headerInfo"));
    }
}
